version: "3.3"

services:
  db:
    restart: always
    image: postgres:16.1-alpine
    container_name: bondi_db_container
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=bondi_local
      - POSTGRES_PASSWORD=bondi_pass01
      - POSTGRES_DB=bondi
      - POSTGRES_PORT=54321
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - bondi_db:/var/lib/postgresql/data

volumes:
  bondi_db:
    driver: local